### PR TITLE
Wrapper for TabSheet and OptionGroup

### PR DESCRIPTION
**Pull request by dve**
plus some smaller commits.

### CODE REVIEW

**Comment by mstahv** [comment]
Nice improvements, thanks! On which add-on are you currently working on? There must be something really cool coming out :-)

**Comment by dve** [comment]
We are not using it for testing an addon, we want to do "full stack" tests for www.vegetweb.de and www.flora-bb.de with it.

**Comment by mstahv** [comment]
Cool, I have just renamed the library wrong :-) Let me know if you want a release to be cut at some point.

**Comment by dve** [comment]
Can you please release?

**Comment by mstahv** [comment]
Done that! Thanks again for your contributions. I added you a direct commit access to the project as well.

**Pull request merged**
